from __future__ import annotations

import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


class DesktopPetFrontendContractTests(unittest.TestCase):
    def test_activity_runtime_keeps_audio_playback_from_message_interruption(self) -> None:
        source = _read("desktop_pet/renderer/services/ActivityRuntime.js")

        self.assertIn("interruptForUserMessage()", source)
        self.assertIn('this._current?.type === "vocal_performance"', source)
        self.assertIn('this._current.status === "running"', source)
        self.assertIn('nextStatus: "interrupted"', source)
        self.assertNotIn('this._current?.type === "audio_playback" && this._current.status === "running"', source)

    def test_activity_runtime_confirms_playback_and_reports_failures(self) -> None:
        source = _read("desktop_pet/renderer/services/ActivityRuntime.js")

        self.assertIn("PLAY_RETRY_DELAYS_MS", source)
        self.assertIn("_playWithConfirmation", source)
        self.assertIn("_waitForPlaybackProgress", source)
        self.assertIn("audio_play_no_progress", source)
        self.assertIn("音频播放动作失败了", source)
        self.assertIn("this._audioEl.muted = false", source)
        self.assertIn("this._audioEl.volume = 1", source)

    def test_desktop_pet_renders_assistant_working_tool_event(self) -> None:
        # Backend emits assistant_working before each tool runs; the streaming
        # frontend must surface it so the pet isn't frozen on "thinking" through
        # a multi-second tool call (CLAUDE.md §9: backend ability != felt UX).
        backend = _read("companion_v01/engine.py")
        tool_rounds = _read("companion_v01/engine_services/tool_rounds.py")
        self.assertIn("build_tool_working_stream_event", backend)
        self.assertIn('"type": "assistant_working"', tool_rounds)

        source = _read("desktop_pet_next/src/main.js")
        self.assertIn('type === "assistant_working"', source)
        self.assertIn("showToolWorking", source)
        # INV-1: a pre-tool line the model already spoke must not be clobbered;
        # the handler only takes the bubble when nothing has been shown yet.
        self.assertIn("hasShownReply", source)

    def test_next_desktop_pet_persists_message_identity_and_renders_queue_receipt(self) -> None:
        source = _read("desktop_pet_next/src/main.js")

        self.assertIn("function createDesktopSourceMessageId()", source)
        self.assertGreaterEqual(source.count("source_message_id: createDesktopSourceMessageId()"), 2)
        self.assertIn('type === "turn_queued"', source)
        self.assertIn("这条消息已排队，稍后会继续回复。", source)

    def test_control_center_settings_have_explicit_v2_owners(self) -> None:
        sources = _read("desktop_pet_next/src/control-center/data-sources.js")
        bridge = _read("desktop_pet_next/src/control-center-v2/bridge.js")
        model_page = _read("desktop_pet_next/src/control-center-v2/components/model.js")
        abilities_page = _read("desktop_pet_next/src/control-center-v2/components/abilities.js")
        system_page = _read("desktop_pet_next/src/control-center-v2/components/system.js")

        self.assertIn("readModelService", sources)
        self.assertIn("runModelServiceAction", sources)
        self.assertIn("runModelServiceBridgeAction", bridge)
        self.assertIn("hasApiKey", model_page)
        self.assertNotIn("apiKeyValue", model_page)
        self.assertIn("abilities.approvalPolicy.save", abilities_page)
        self.assertIn('data-capability-form="provider"', abilities_page)
        self.assertIn('data-capability-form="mcp"', abilities_page)
        self.assertIn('data-capability-form="workflow"', abilities_page)
        self.assertIn("Skill 操作手册", abilities_page)
        self.assertIn("abilities.skills.openFolder", abilities_page)
        self.assertIn("abilities.approvalRequest.decide", _read("desktop_pet_next/src/control-center/action-router.js"))
        self.assertIn("item.actionId", system_page)

    def test_workspace_panel_opens_local_location_instead_of_browser_download(self) -> None:
        source = _read("desktop_pet/renderer/ui/WorkspacePanel.js")

        self.assertIn("fetchWorkspaceItemLocation", source)
        self.assertIn("showItemInFolder", source)
        self.assertNotIn("openExternal", source)
        self.assertNotIn("open-external", source)
        self.assertIn('action: "clear_files"', source)
        self.assertIn("清理了", source)
        self.assertIn("源文件和生成文件", source)

    def test_presentation_controller_keeps_formal_reply_priority_and_segment_precedence(self) -> None:
        source = _read("desktop_pet/renderer/services/PresentationController.js")

        self.assertIn("const SOURCE_PRIORITY", source)
        self.assertIn("formal: 3", source)
        self.assertIn('source !== "formal" && this.isFormalActive()', source)
        self.assertIn("this.canAcceptPassive()", source)
        self.assertIn("queue: true", source)
        self.assertLess(
            source.index("const segments = this._normalizeSegments"),
            source.index("const speech = String"),
        )
        self.assertIn('source: "speech_segments"', source)

    def test_settings_defaults_are_safe_for_productized_desktop_pet(self) -> None:
        source = _read("desktop_pet/main/settings-store.js")

        self.assertIn('backendUrl: "http://127.0.0.1:9999"', source)
        self.assertIn('outfit: "猫娘"', source)
        self.assertIn("voiceEnabled: false", source)
        self.assertIn("voiceInputEnabled: true", source)
        self.assertIn("clipboardContextEnabled: false", source)
        self.assertIn('["水手服", "睡衣"].includes(outfit)', source)

    def test_pet_scale_is_persisted_and_drives_window_and_renderer_layout(self) -> None:
        settings_store = _read("desktop_pet/main/settings-store.js")
        window_source = _read("desktop_pet/main/window.js")
        app_source = _read("desktop_pet/renderer/app.js")
        settings_page = _read("desktop_pet/renderer/settings.js")
        context_menu = _read("desktop_pet/renderer/ui/ContextMenu.js")
        styles = _read("desktop_pet/renderer/styles.css")

        self.assertIn("petScale: 1", settings_store)
        self.assertIn("PET_SCALE_VALUES", settings_store)
        self.assertIn("normalizePetScale", settings_store)
        self.assertIn("getPetWindowSize", window_source)
        self.assertIn("applyPetScaleBounds", window_source)
        self.assertIn("resolveWindowBounds(settings.windowBounds, settings.petScale)", window_source)

        self.assertIn('style.setProperty("--pet-scale"', app_source)
        self.assertIn("chatInput.refreshLayout", app_source)
        self.assertIn('"set-pet-scale"', app_source)
        self.assertIn("petScale: currentPetScale", app_source)

        self.assertIn("大小与占用", settings_page)
        self.assertIn('data-field="petScale"', settings_page)
        self.assertIn("normalizePetScale", settings_page)
        self.assertIn('data-action="set-pet-scale"', context_menu)

        self.assertIn("--pet-scale", styles)
        self.assertIn("--chat-input-min-height", styles)
        self.assertIn("calc(318px * var(--pet-scale))", styles)
        self.assertIn("calc(324px * var(--pet-scale))", styles)

    def test_next_music_queue_has_visible_management_surfaces(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")
        control_center_source = _read("desktop_pet_next/src/control-center-v2/components/overview.js")
        workspace_source = _read("desktop_pet_next/src/workspace.js")
        workspace_html = _read("desktop_pet_next/workspace.html")
        tauri_source = _read("desktop_pet_next/src-tauri/src/main.rs")

        self.assertIn("playMusicTrackBySourceId", main_source)
        self.assertIn("removeMusicTrackBySourceId", main_source)
        self.assertIn("parseLrcText", main_source)
        self.assertIn("buildCurrentLyricSnapshot", main_source)
        self.assertIn("lyric_current", main_source)
        self.assertIn("scheduleBackendMusicTimeline", main_source)
        self.assertIn("uploadMusicTrackForTimeline", main_source)
        self.assertIn("prepareBackendMusicTimeline", main_source)
        self.assertIn("MUSIC_TIMELINE_INITIAL_DELAY_MS", main_source)
        self.assertIn("/desktop-pet/attachments/audio", main_source)
        self.assertIn("/desktop-pet/music-timeline/prepare", main_source)
        self.assertIn("importDroppedFilesToWorkspace", main_source)
        self.assertIn("pendingAttachments.add(result.items, draftScope)", main_source)
        self.assertIn("current_attachment_ids: attachmentIds", main_source)
        self.assertNotIn("runDroppedWorkspaceImportInBackground", main_source)
        self.assertIn('"import_dropped_files"', main_source)
        self.assertNotIn("/desktop-pet/workspace/import-local", main_source)
        self.assertIn('const BASE_CAPABILITIES = ["speech_segments", "tts", "file_drop", "tool_actions"]', main_source)
        self.assertIn("function getProfileUserId()", main_source)
        self.assertIn("real_user_id: getProfileUserId()", main_source)
        self.assertNotIn("real_user_id: PROFILE_USER_ID", main_source)
        self.assertIn("WORKSPACE_REFRESH_EVENT", main_source)
        self.assertIn("showFileDropHint", main_source)
        self.assertNotIn("scheduleWorkspaceTaskWatch", main_source)
        self.assertNotIn("announceWorkspaceTaskChanges", main_source)
        self.assertIn("/desktop-pet/workspace/summary", main_source)
        self.assertIn("handleDesktopFileDeliveryEvent", main_source)
        self.assertIn("applyPayloadFileDeliveries", main_source)
        self.assertIn("handleBrowserOpenEvent", main_source)
        self.assertIn("browser_open_requested", main_source)
        self.assertIn('tauriCall("open_external_url"', main_source)
        self.assertIn("delivery_action", main_source)
        self.assertIn('tauriCall("open_workspace_item"', main_source)
        self.assertIn('action: "stage"', main_source)
        self.assertNotIn('tauriCall("open_local_file"', main_source)
        self.assertNotIn('tauriCall("show_item_in_folder"', main_source)
        self.assertIn("timelineLyricLineCount", main_source)
        self.assertIn('"playMusicTrack"', main_source)
        self.assertIn('"removeMusicTrack"', main_source)
        self.assertIn("async fn prepare_audio_asset", tauri_source)
        self.assertIn("spawn_blocking(move ||", tauri_source)
        self.assertIn("fn prepare_audio_asset_blocking", tauri_source)
        self.assertIn("function renderMusic(state, vm)", control_center_source)
        self.assertIn('class="music-card glass-panel"', control_center_source)
        self.assertIn('renderActionButton(state, vm, "music.togglePlayback"', control_center_source)
        self.assertNotIn("data-music-progress-track", control_center_source)
        self.assertNotIn("data-music-volume-track", control_center_source)
        self.assertIn('id="workspace-music"', workspace_html)
        self.assertIn("renderMusicPanel", workspace_source)
        self.assertIn("buildMusicLyricText", workspace_source)
        self.assertIn("WORKSPACE_REFRESH_EVENT", workspace_source)
        self.assertIn("scheduleWorkspaceRefresh(120)", workspace_source)
        self.assertNotIn("TASK_AUTO_REFRESH_MS", workspace_source)
        self.assertIn("resolveItemStatusGroup", workspace_source)
        self.assertNotIn("sections.tasks", workspace_source)
        self.assertIn("SETTINGS_COMMAND_EVENT", workspace_source)
        self.assertIn("openWorkspaceItem", workspace_source)
        self.assertIn("revealWorkspaceItem", workspace_source)
        self.assertIn("copyWorkspaceItemPath", workspace_source)
        self.assertIn("exportWorkspaceItemToDesktop", workspace_source)
        self.assertIn("invokeWorkspaceItemAction", workspace_source)
        self.assertIn('invoke("open_workspace_item"', workspace_source)
        self.assertIn("real_user_id", workspace_source)
        self.assertNotIn("resolveWorkspaceItemPath", workspace_source)
        self.assertNotIn('invoke("open_local_file"', workspace_source)
        self.assertNotIn('invoke("show_item_in_folder"', workspace_source)
        self.assertIn("fn open_local_file", tauri_source)
        self.assertIn("fn show_item_in_folder", tauri_source)
        self.assertIn("fn open_external_url", tauri_source)
        self.assertIn("fn normalize_public_external_url", tauri_source)
        self.assertIn("fn export_file_to_desktop", tauri_source)
        self.assertIn("Akane Outputs", tauri_source)

    def test_next_tts_queue_prefetches_next_audio_while_playing_current(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")

        self.assertIn("function startNextTtsPrepare(token)", main_source)
        self.assertIn("function queueStreamedTtsSegment(text, turnToken, segmentIndex = null)", main_source)
        self.assertIn("function queueStreamedReplySegment(text, turnToken)", main_source)
        self.assertIn('function queueLiveTtsPayloadItems(items, signature = "")', main_source)
        self.assertIn("function createTurnLatencyTrace(kind, turnToken, details = {})", main_source)
        self.assertIn('storage?.getItem("akane.debug.turn") === "1"', main_source)
        self.assertNotIn("collectDesktopContextForTurn", main_source)
        self.assertNotIn("buildCachedDesktopContextForTurn", main_source)
        self.assertNotIn("navigator.clipboard.readText", main_source)
        self.assertIn('markTurnLatency("think-request-start")', main_source)
        self.assertNotIn("function displayStreamingReplyPreview(text)", main_source)
        self.assertIn('markTurnLatencyOnce("first-speech-segment"', main_source)
        self.assertIn("function removeStreamingTtsPrefix(text)", main_source)
        self.assertNotIn("function removeStreamingReplyPrefix(text)", main_source)
        self.assertIn("function resetStreamedReplySegments(turnToken = 0)", main_source)
        self.assertIn("function missingFinalReplySegments(segments)", main_source)
        self.assertIn("streamedReplyTexts = []", main_source)
        self.assertIn("els.bubbleText.scrollTop = 0", main_source)
        self.assertIn("function displayReplyBubbleText(text, { speaking = true } = {})", main_source)
        self.assertIn("function getSegmentDisplayDelay(text)", main_source)
        self.assertIn("if (!rendered && !backgroundObservation) {\n        showThinking();", main_source)
        self.assertIn("queueStreamedReplySegment(text, turnToken)", main_source)
        self.assertIn("rendered = true;", main_source)
        self.assertIn('if (!rendered && bubbleKind === "thinking")', main_source)
        self.assertIn("queueStreamedTtsSegment(text, turnToken, acceptedSpeechIndex++)", main_source)
        self.assertIn("for (const segment of missingFinalReplySegments(finalSegments))", main_source)
        self.assertIn("suppressSpeech: hasStreamedReply", main_source)
        self.assertIn("bufferStreamingTtsSegment(normalized, turnToken, segmentKey)", main_source)
        self.assertIn("function flushStreamingTtsPending", main_source)
        self.assertIn("const TTS_SHORT_SEGMENT_MAX_CHARS = 4", main_source)
        self.assertIn("const TTS_SHORT_SEGMENT_HOLD_MS = 420", main_source)
        self.assertIn("queueLiveTtsPayloadItems(segments, signature)", main_source)
        self.assertIn('const TTS_PREWARM_TEXT = "嗯。"', main_source)
        self.assertIn(
            "function scheduleTtsPrewarm({ force = false, delayMs = TTS_PREWARM_DELAY_MS } = {})", main_source
        )
        self.assertIn("function cancelTtsPrewarm()", main_source)
        self.assertIn("async function runTtsPrewarm({ force = false } = {})", main_source)
        self.assertIn("scheduleTtsPrewarm({ force: true, delayMs: 200 })", main_source)
        self.assertIn("scheduleTtsPrewarm({ delayMs: startup ? 900 : 300 })", main_source)
        self.assertIn("cancelTtsPrewarm();\n  stopTts();", main_source)
        self.assertIn("ttsPrewarmReadyAtByKey.set(key, Date.now())", main_source)
        self.assertIn('logTtsTiming("prewarm-ready"', main_source)
        self.assertGreaterEqual(main_source.count("signal: controller.signal"), 2)
        self.assertIn("async function fetchTtsAudio(text, token)", main_source)
        self.assertIn("async function playPreparedTtsAudio(prepared, token, { reply = false, displayText = \"\" } = {})", main_source)
        self.assertIn("function discardPendingTtsPrepare(pendingPrepared)", main_source)
        self.assertIn("resetStreamingTtsState(turnToken)", main_source)
        self.assertIn("resetStreamedReplySegments(turnToken)", main_source)
        self.assertIn("streamingTtsSegmentKeys.clear()", main_source)
        self.assertNotIn("streamingReplySegmentKeys", main_source)
        self.assertIn("TTS_SLOW_REQUEST_MS", main_source)
        self.assertIn("const TTS_CHUNK_SOFT_LIMIT = 24", main_source)
        self.assertIn("segmentSpeechForDelivery", main_source)
        self.assertIn('"./speech-delivery.js"', main_source)
        self.assertIn("function splitTtsTextForLatency(text)", main_source)
        self.assertIn(
            "segmentSpeechForDelivery(normalized, { minChars: 1, maxChars: TTS_CHUNK_SOFT_LIMIT })",
            main_source,
        )
        self.assertIn(
            'function queueTtsItems(items, signature = "", { append = false, preserveSegments = false, reply = false } = {})',
            main_source,
        )
        self.assertIn("function buildTtsQueueItems(items, { preserveSegments = false } = {})", main_source)
        self.assertIn("item.length > TTS_CHUNK_SOFT_LIMIT ? splitTtsTextForLatency(item) : [item]", main_source)
        self.assertIn("queueTtsItems(normalized, signature, { reply: true });", main_source)
        self.assertIn("ttsQueue.push(...nextItems)", main_source)
        self.assertIn('setRuntimeStatus("语音生成中…"', main_source)
        self.assertIn('logTtsTiming("prepared"', main_source)
        self.assertIn("pendingPrepared = startNextTtsPrepare(token);", main_source)
        self.assertIn("prefetch();", main_source)
        self.assertLess(
            main_source.index("prefetch();"),
            main_source.index("await playPreparedTtsAudio(prepared.audio, token, {"),
        )

    def test_next_realtime_voice_uses_pcm_and_real_playback_acknowledgements(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")
        client_source = _read("desktop_pet_next/src/realtime-voice-client.js")
        call_flow_source = _read("desktop_pet_next/src/realtime-voice-call-flow.js")
        endpoint_source = _read("desktop_pet_next/src/realtime-voice-endpoint.js")
        worklet_source = _read("desktop_pet_next/src/voice-pcm-worklet.js")

        self.assertIn("new RealtimeVoiceSession", main_source)
        self.assertIn('buildBackendEndpointUrl("voiceRealtime", "/voice/realtime"', main_source)
        self.assertIn("fallbackRealtimeVoiceToBatch", main_source)
        self.assertIn("turn.fallbackBlob = turn.committed ? null : blob", main_source)
        self.assertIn("REALTIME_VOICE_FINAL_TIMEOUT_MS", main_source)
        self.assertIn("armRealtimeVoiceFinalWatchdog(turn)", main_source)
        self.assertIn('reason: "voice_realtime_final_timeout"', main_source)
        self.assertIn("transcribeVoiceBlob(blob, { autoSubmit: true })", main_source)
        self.assertIn("await sendMessage(text)", main_source)
        self.assertIn('reason: "user_started_voice_input"', main_source)
        self.assertIn("if (isReplyActive())", main_source)
        self.assertIn("上一轮已停下，正在听你说", main_source)
        self.assertNotIn("等一下再听你说", main_source)
        self.assertIn('format: "f32le"', client_source)
        self.assertIn('type: "client.audio"', client_source)
        self.assertIn('type: "client.endpoint"', client_source)
        self.assertIn('type: "client.playback.enqueued"', client_source)
        self.assertIn('type: "client.playback.started"', client_source)
        self.assertIn('"client.playback.completed"', client_source)
        self.assertIn('type: "client.playback.control_ack"', client_source)
        self.assertIn('type === "server.playback.control"', client_source)
        self.assertIn("class RealtimeVoiceCallResources", client_source)
        self.assertIn("new RealtimeVoiceCallResources", main_source)
        self.assertIn("new RealtimeVoiceCallFlow", main_source)
        self.assertIn("new RealtimeVoiceEndpointDetector", main_source)
        self.assertIn("async function startRealtimeVoiceCall()", main_source)
        self.assertIn("async function stopRealtimeVoiceCall(", main_source)
        self.assertIn('els.voiceRecordButton.textContent = "挂"', main_source)
        self.assertIn("turn.call.flow?.acceptEndpoint(turn.flowTurn, action)", main_source)
        self.assertIn("turn.call.flow?.allowOverlapListening(turn.flowTurn)", main_source)
        self.assertIn("const call = turn.call", main_source)
        self.assertIn("call.flow?.complete(turn.flowTurn)", main_source)
        self.assertIn("call.flow?.stop()", main_source)
        self.assertIn("class RealtimeVoiceCallFlow", call_flow_source)
        self.assertIn("turn.endpointAccepted", call_flow_source)
        self.assertIn("this.requestNextListeningTurn()", call_flow_source)
        self.assertIn("allowOverlapListening(turn)", call_flow_source)
        self.assertIn("voice_call_capture_busy", client_source)
        self.assertIn('requestCaptureReceipt("reset")', client_source)
        self.assertIn("this.endpointDetector?.acceptPcmFrame", client_source)
        self.assertIn("this.endpointDetector?.observeTranscript", client_source)
        self.assertIn('type: "client.interruption.suspected"', client_source)
        self.assertIn("reportInterruptionSuspected()", client_source)
        self.assertIn("class RealtimeVoiceEndpointDetector", endpoint_source)
        self.assertIn('"stable_checkpoint_silence"', endpoint_source)
        self.assertIn('"speech_without_transcript"', endpoint_source)
        self.assertIn("this.audioElement.volume = clampVolume(appliedVolume)", client_source)
        self.assertIn("this.audioElement.pause();", client_source)
        self.assertIn("onPlaybackDucked", main_source)
        self.assertIn("onPlaybackResumed", main_source)
        self.assertLess(
            client_source.index("await audioElement.play();"),
            client_source.index('type: "client.playback.started"'),
        )
        self.assertIn('audioElement.addEventListener("ended"', client_source)
        self.assertIn('registerProcessor("akane-voice-pcm-capture"', worklet_source)
        self.assertIn("new Float32Array", worklet_source)
        self.assertIn('type === "reset"', worklet_source)
        self.assertIn("this.pendingLength = 0", worklet_source)
        self.assertNotIn("MediaRecorder", worklet_source)

    def test_next_tauri_heavy_file_commands_run_on_blocking_worker(self) -> None:
        tauri_source = _read("desktop_pet_next/src-tauri/src/main.rs")
        blocking_commands = [
            "prepare_audio_asset",
            "install_character_pack_zip_file",
            "install_character_pack_zip_bytes",
            "export_file_to_desktop",
            "upload_portrait_image",
            "import_generated_portrait_image",
            "read_portrait_image",
            "export_character_pack",
        ]

        for command in blocking_commands:
            wrapper_index = tauri_source.index(f"async fn {command}")
            blocking_index = tauri_source.index(f"fn {command}_blocking", wrapper_index)
            wrapper_source = tauri_source[wrapper_index:blocking_index]
            self.assertIn("spawn_blocking(move ||", wrapper_source)

    def test_next_generated_portrait_import_command_uses_safe_atomic_write(self) -> None:
        tauri_source = _read("desktop_pet_next/src-tauri/src/main.rs")

        self.assertIn("async fn import_generated_portrait_image", tauri_source)
        self.assertIn("fn import_generated_portrait_image_blocking", tauri_source)
        self.assertIn("import_generated_portrait_image,", tauri_source)

        wrapper_index = tauri_source.index("async fn import_generated_portrait_image")
        blocking_index = tauri_source.index("fn import_generated_portrait_image_blocking", wrapper_index)
        wrapper_source = tauri_source[wrapper_index:blocking_index]
        self.assertIn("spawn_blocking(move ||", wrapper_source)

        end_index = tauri_source.index("#[tauri::command]\nfn create_portrait_outfit", blocking_index)
        blocking_source = tauri_source[blocking_index:end_index]
        self.assertIn("let outfit = sanitize_asset_id(&outfit)", blocking_source)
        self.assertIn("let emotion = sanitize_asset_id(&emotion)", blocking_source)
        self.assertIn("safe_child_path(&characters_dir, &pack_id)", blocking_source)
        self.assertIn("safe_child_path(&characters_dir, &outfit)", blocking_source)
        self.assertIn('safe_child_path(&outfit_dir, &format!("{emotion}.{extension}"))', blocking_source)
        self.assertIn(
            "write_bytes_atomic_with_cleanup(&target_path, &image_bytes, &cleanup_paths)",
            blocking_source,
        )
        self.assertIn("Ok(list_character_pack_outfits(&pack_dir, &asset_root))", blocking_source)

        writer_index = tauri_source.index("fn write_bytes_atomic")
        safe_path_index = tauri_source.index("fn safe_child_path", writer_index)
        writer_source = tauri_source[writer_index:safe_path_index]
        self.assertIn('let tmp_path = parent.join(format!(".{file_name}.tmp"))', writer_source)
        self.assertIn("fs::rename(&tmp_path, path)", writer_source)

    def test_character_pack_install_commands_remain_owned_by_tauri_and_workshop(self) -> None:
        control_center_source = _read("desktop_pet_next/src/control-center-v2/components/overview.js")
        workshop_source = _read("desktop_pet_next/src/workshop.js")
        tauri_source = _read("desktop_pet_next/src-tauri/src/main.rs")
        main_source = _read("desktop_pet_next/src/main.js")

        self.assertIn('"character.openWorkshop"', control_center_source)
        self.assertNotIn("characterImportZip", control_center_source)
        self.assertIn('invoke("install_character_pack_zip_bytes"', workshop_source)
        self.assertIn('invoke("open_character_packs_folder"', workshop_source)
        self.assertIn("fn install_character_pack_zip", tauri_source)
        self.assertIn("fn list_character_packs", tauri_source)
        self.assertIn("list_character_packs", tauri_source)
        self.assertIn("install_character_pack_zip_bytes", tauri_source)
        self.assertIn("install_character_pack_zip_file", tauri_source)
        self.assertIn("open_path_in_file_manager", tauri_source)
        self.assertIn("DEFAULT_CHARACTER_PACK_ID", tauri_source)
        self.assertIn('"refreshCharacterPacks"', main_source)
        self.assertIn("setRuntimeCharacterPacks", main_source)
        self.assertIn("character_pack_id: getCurrentCharacterPackId()", main_source)
        self.assertIn("client: CLIENT_MODE", main_source)
        self.assertIn("function getCurrentCharacterPackId()", main_source)

    def test_character_pack_private_local_data_is_not_exported_or_overwritten(self) -> None:
        tauri_source = _read("desktop_pet_next/src-tauri/src/main.rs")
        exporter_source = _read("desktop_pet_creator_kit/scripts/export-character-pack.mjs")
        importer_source = _read("desktop_pet_creator_kit/scripts/import-character-pack.mjs")
        validator_source = _read("desktop_pet_creator_kit/scripts/validate-character-pack.mjs")

        self.assertIn('const PRIVATE_LOCAL_DIRECTORY: &str = "_local";', tauri_source)
        self.assertIn("name.eq_ignore_ascii_case(PRIVATE_LOCAL_DIRECTORY)", tauri_source)
        self.assertIn("is_private_local_relative_path(relative)", tauri_source)
        self.assertIn("fs::rename(&destination, &backup)", tauri_source)
        self.assertIn("fs::rename(&previous_local, &installed_local)", tauri_source)

        self.assertIn('const PRIVATE_LOCAL_DIRECTORY = "_local";', exporter_source)
        self.assertIn("entry.name.toLowerCase() === PRIVATE_LOCAL_DIRECTORY", exporter_source)
        self.assertIn("restorePrivateLocalDirectory(backupPath, destination)", importer_source)
        self.assertIn("isPrivateLocalPath(relativePath)", importer_source)
        self.assertIn('folder.toLowerCase() === "_local"', validator_source)

    def test_next_settings_exposes_readonly_desktop_diagnostics(self) -> None:
        control_center_source = _read("desktop_pet_next/src/control-center-v2/components/system.js")
        bridge = _read("desktop_pet_next/src/control-center-v2/bridge.js")
        data_source = _read("desktop_pet_next/src/control-center/data-sources.js")
        control_center_css = _read("desktop_pet_next/src/control-center-v2/styles.css")

        self.assertIn("@tauri-apps/plugin-http", bridge)
        self.assertIn("export function renderSystem", control_center_source)
        self.assertIn("ccv2-system", control_center_source)
        self.assertIn('buildBackendUrl(botBaseUrl, "/desktop-pet/diagnostics"', data_source)
        self.assertIn("character_pack_id", data_source)
        self.assertIn("real_user_id", data_source)
        self.assertIn(".ccv2-system", control_center_css)

    def test_control_center_abilities_reads_capability_catalog_as_dashboard(self) -> None:
        data_source = _read("desktop_pet_next/src/control-center/data-sources.js")
        control_center_source = _read("desktop_pet_next/src/control-center-v2/components/abilities.js")
        control_center_css = _read("desktop_pet_next/src/control-center-v2/styles.css")
        runtime_probe = _read("desktop_pet_next/scripts/control-center-runtime-probe.mjs")

        self.assertIn('buildBackendUrl(baseUrl, "/capabilities"', data_source)
        self.assertIn("approvalPolicyBackendActionIds", data_source)
        self.assertIn("abilities.approvalPolicy.save", control_center_source)
        self.assertIn("data-approval-mode", control_center_source)
        self.assertIn("能力目录还没有同步", control_center_source)
        self.assertIn(".ccv2-abilities", control_center_css)
        self.assertIn("capabilityCatalog", runtime_probe)
        self.assertFalse((ROOT / "desktop_pet_next/src/control-center/data-adapter.js").exists())
        self.assertFalse((ROOT / "desktop_pet_next/src/control-center/mock-data.js").exists())
        self.assertFalse((ROOT / "desktop_pet_next/src/control-center/snapshot-schema.js").exists())
        self.assertFalse((ROOT / "desktop_pet_next/src/control-center/action-surface-contract.js").exists())

    def test_next_settings_uses_control_center_navigation_layout(self) -> None:
        compatibility_module = _read("desktop_pet_next/src/control-center-lab.js")
        control_center_source = _read("desktop_pet_next/src/control-center-v2/components/shell.js")
        control_center_index = _read("desktop_pet_next/src/control-center-v2/index.js")
        control_center_html = _read("desktop_pet_next/control-center-lab.html")
        compatibility_html = _read("desktop_pet_next/settings.html")
        v2_compatibility_html = _read("desktop_pet_next/control-center-v2.html")
        control_center_css = _read("desktop_pet_next/src/control-center-v2/styles.css")
        tauri_source = _read("desktop_pet_next/src-tauri/src/main.rs")
        tauri_capabilities = _read("desktop_pet_next/src-tauri/capabilities/default.json")

        self.assertIn('id="app"', control_center_html)
        self.assertIn('src="/src/control-center-v2/index.js"', control_center_html)
        self.assertIn('import "./control-center-v2/index.js"', compatibility_module)
        self.assertIn("export function renderControlCenterShell", control_center_source)
        self.assertIn("renderOverview", control_center_source)
        self.assertIn("renderModelService", control_center_source)
        self.assertIn("renderCharacterAppearance", control_center_source)
        self.assertIn("renderSystem", control_center_source)
        self.assertIn('class="ccv2-rail"', control_center_source)
        self.assertIn('class="window-actions"', control_center_source)
        self.assertIn('"window.minimize"', control_center_source)
        self.assertIn('"window.maximize"', control_center_source)
        self.assertIn('"window.close"', control_center_source)
        self.assertIn("initialPageFromLocation", control_center_index)
        self.assertIn(".ccv2-rail", control_center_css)
        self.assertIn(".window-actions", control_center_css)
        self.assertIn("./control-center-lab.html", compatibility_html)
        self.assertIn("window.location.replace(target.href)", compatibility_html)
        self.assertNotIn("/src/settings.js", compatibility_html)
        self.assertIn("control-center-lab.html", v2_compatibility_html)
        self.assertNotIn('id="app"', v2_compatibility_html)
        self.assertIn(".inner_size(1080.0, 720.0)", tauri_source)
        self.assertIn(".min_inner_size(760.0, 560.0)", tauri_source)
        self.assertIn(".decorations(false)", tauri_source)
        self.assertNotIn("AKANE_LEGACY_SETTINGS", tauri_source)
        self.assertIn('"control-center-lab.html?page=model"', tauri_source)
        self.assertIn('"control-center-lab.html"', tauri_source)
        self.assertNotIn("AKANE_CONTROL_CENTER_ENTRY", tauri_source)
        self.assertIn("core:window:allow-close", tauri_capabilities)
        self.assertIn("core:window:allow-minimize", tauri_capabilities)
        self.assertIn("core:window:allow-toggle-maximize", tauri_capabilities)
        self.assertFalse((ROOT / "desktop_pet_next/src/settings.js").exists())
        self.assertFalse((ROOT / "desktop_pet_next/src/settings.css").exists())
        self.assertFalse((ROOT / "desktop_pet_next/src/control-center-lab.css").exists())

    def test_next_character_workshop_repair_contracts(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")
        workshop_html = _read("desktop_pet_next/workshop.html")
        workshop_source = _read("desktop_pet_next/src/workshop.js")
        workshop_css = _read("desktop_pet_next/src/workshop.css")
        tauri_source = _read("desktop_pet_next/src-tauri/src/main.rs")
        tauri_capabilities = _read("desktop_pet_next/src-tauri/capabilities/default.json")

        self.assertNotIn("characterPackRegistry", main_source)
        self.assertIn("const profile = getActiveCharacterProfile()", main_source)
        self.assertIn("visualRenderer.setLayout(null)", main_source)

        main_close = workshop_html.rfind("</main>")
        self.assertGreater(main_close, 0)
        self.assertLess(workshop_html.index('data-tab-panel="portraits"'), main_close)
        self.assertLess(workshop_html.index('data-tab-panel="calibration"'), main_close)
        self.assertLess(workshop_html.index('data-tab-panel="test"'), main_close)
        self.assertIn('data-tab="test"', workshop_html)
        self.assertIn('id="test-chat-form"', workshop_html)
        self.assertIn('id="test-scope-profile"', workshop_html)
        self.assertIn('id="test-apply-pack"', workshop_html)
        self.assertIn('id="test-visual-preview"', workshop_html)
        self.assertIn('id="first-use-panel"', workshop_html)
        self.assertIn('id="first-use-create"', workshop_html)
        self.assertIn('id="first-use-import"', workshop_html)
        self.assertIn('id="detail-edit-pack"', workshop_html)
        self.assertIn('id="detail-test-pack"', workshop_html)
        self.assertNotIn("后端保存功能将在后续版本开放", workshop_html)
        self.assertNotIn(' style="', workshop_html)
        self.assertIn('id="cal-bubble-style"', workshop_html)
        self.assertIn('data-cal-bubble-style="soft"', workshop_html)
        self.assertIn('id="field-app-name"', workshop_html)
        self.assertIn('id="field-character-core"', workshop_html)
        self.assertIn('id="field-behavior-style"', workshop_html)
        self.assertIn('id="field-interaction-principles"', workshop_html)
        self.assertIn('id="new-outfit-id"', workshop_html)
        self.assertIn('id="portrait-cutout-status"', workshop_html)
        self.assertIn('id="portrait-cutout-summary"', workshop_html)
        self.assertIn('id="portrait-cutout-config"', workshop_html)
        self.assertIn('id="portrait-cutout-run"', workshop_html)
        self.assertIn("透明背景处理", workshop_html)

        self.assertIn('import { fetch as tauriFetch } from "@tauri-apps/plugin-http"', workshop_source)
        self.assertIn('const CLIENT_MODE = "desktop_pet"', workshop_source)
        self.assertIn('const WORKSHOP_TEST_SCOPE_PREFIX = "workshop_test"', workshop_source)
        self.assertIn('const PORTRAIT_CUTOUT_WORKFLOW_ID = "workflow.workshop.portrait.cutout"', workshop_source)
        self.assertIn("PORTRAIT_CUTOUT_CAPABILITY_CACHE_MS", workshop_source)
        self.assertIn('buildBackendUrl("/capabilities/workflows"', workshop_source)
        self.assertIn("function refreshPortraitCutoutCapability(options = {})", workshop_source)
        self.assertIn("function normalizePortraitCutoutCapability(workflow)", workshop_source)
        self.assertIn("function describePortraitCutoutReason(reason)", workshop_source)
        self.assertIn("workflow_file_missing", workshop_source)
        self.assertIn("slot_mapping_path_invalid", workshop_source)
        self.assertIn("ComfyUI 请求失败", workshop_source)
        self.assertIn("function renderPortraitCutoutStatus()", workshop_source)
        self.assertIn('invoke("open_settings_window")', workshop_source)
        self.assertNotIn("/capabilities/workflows/run", workshop_source)
        self.assertNotIn("workshop.portrait.cutout/run", workshop_source)
        self.assertNotIn("executePortraitCutout", workshop_source)
        self.assertIn("async function runPortraitCutoutForPreview()", workshop_source)
        self.assertIn("buildBackendUrl(`/capabilities/workflows/${PORTRAIT_CUTOUT_WORKFLOW_ID}/jobs`", workshop_source)
        self.assertIn("buildBackendUrl(`/capabilities/workflow-jobs/${jobId}`", workshop_source)
        self.assertIn("buildBackendUrl(`/capabilities/workflow-jobs/${jobId}/outputs/${outputHandle}`", workshop_source)
        self.assertIn('invoke("import_generated_portrait_image"', workshop_source)
        self.assertIn("readPortraitImageBytes(packId, outfitId, emotionId)", workshop_source)
        self.assertIn("overwrite: false", workshop_source)
        self.assertIn('buildBackendUrl("/think"', workshop_source)
        self.assertIn('turn_kind: "workshop_test_chat"', workshop_source)
        self.assertIn("user_id: scope.sessionId", workshop_source)
        self.assertIn("session_id: scope.sessionId", workshop_source)
        self.assertIn("real_user_id: scope.profileUserId", workshop_source)
        self.assertIn("character_pack_id: pack.id", workshop_source)
        self.assertNotIn("user_id: view.activeSessionId", workshop_source)
        think_request_start = workshop_source.index("async function requestWorkshopThink")
        think_request_end = workshop_source.index("async function consumeWorkshopThinkStream", think_request_start)
        think_request_source = workshop_source[think_request_start:think_request_end]
        self.assertNotIn("real_user_id: view.profileUserId", think_request_source)
        self.assertIn('real_user_id: view.profileUserId || "master"', workshop_source)
        self.assertIn("async function saveDraft(options = {})", workshop_source)
        self.assertIn("const allowLocalFallback = options.allowLocalFallback !== false", workshop_source)
        self.assertIn('invoke("save_character_pack", {', workshop_source)
        self.assertIn("request: {\n            packId,", workshop_source)
        self.assertIn("dialogue: exampleLines.length ? { local_click_lines: exampleLines } : null", workshop_source)
        self.assertIn("dialogue: data.dialogue", workshop_source)
        self.assertIn("示例 / 点击反馈台词", workshop_html)
        self.assertIn('invoke("create_character_pack", {', workshop_source)
        self.assertIn("request: {\n        packId,", workshop_source)
        self.assertIn('data-tab="context"', workshop_html)
        self.assertIn("提示词里会看到什么", workshop_html)
        self.assertIn("你只需要往新文件夹里放以主题命名的 .md 文件", workshop_html)
        self.assertIn('invoke("create_character_context_library", {', workshop_source)
        self.assertIn("function renderContextLibraries", workshop_source)
        self.assertIn("fn create_character_context_library", tauri_source)
        self.assertIn('entry("context_libraries".to_string())', tauri_source)
        self.assertIn("sanitize_context_library_folder", tauri_source)
        self.assertIn("fn set_character_voice_profile", tauri_source)
        self.assertIn("fn clear_character_voice_profile", tauri_source)
        self.assertIn("sanitize_voice_profile_id", tauri_source)
        self.assertIn("normalize_character_voice_provider", tauri_source)
        self.assertIn("dialogue: serde_json::Value", tauri_source)
        self.assertIn('entry("dialogue".to_string())', tauri_source)
        self.assertIn("deep_merge_json(dialogue, &request.dialogue)", tauri_source)
        self.assertIn("write_text_atomic(&character_path, &updated)", tauri_source)
        self.assertIn("set_character_voice_profile,", tauri_source)
        self.assertIn("clear_character_voice_profile,", tauri_source)
        self.assertIn("function hasBackendPendingPersonaChanges(packId)", workshop_source)
        self.assertIn("(view.editingPackId === id && view.draftDirty) || hasDraft(id)", workshop_source)
        self.assertIn("if (hasBackendPendingPersonaChanges(packId))", workshop_source)
        self.assertIn("await saveDraft({ allowLocalFallback: false, packId })", workshop_source)
        self.assertIn("测试已暂停：当前人设没有写入角色包文件。", workshop_source)
        self.assertIn("function applyTestPackToDesktop", workshop_source)
        self.assertIn('invoke("activate_character_pack", { packId })', workshop_source)
        self.assertIn("function buildTestCurrentVisual", workshop_source)
        self.assertIn("layout: visual.layout || null", workshop_source)
        self.assertIn("view.testAssetsByPack", workshop_source)
        self.assertIn("function mergeSnapshotPacks", workshop_source)
        self.assertIn("hasProfilePayload(pack._rawProfile) ? pack._rawProfile : existing._rawProfile", workshop_source)
        self.assertIn("workspacePackId", workshop_source)
        self.assertIn("state.characterPackId || character.packId", workshop_source)
        self.assertNotIn("waitForPackApplication", workshop_source)
        self.assertNotIn("handlePackApplicationResult", workshop_source)
        self.assertNotIn("CHARACTER_APPLY_RESULT_EVENT", workshop_source)
        self.assertNotIn("pendingApplyTimer", workshop_source)
        self.assertIn("桌宠正在使用 · 工坊正在编辑", workshop_source)
        self.assertNotIn("pack.id === view.activePackId || Boolean(pack.selected)", workshop_source)
        self.assertNotIn("view.editingPackId !== view.activePackId", workshop_source)
        self.assertIn('id="editing-character"', workshop_html)
        self.assertIn("fieldAppName: document.querySelector", workshop_source)
        self.assertIn("character_core:", workshop_source)
        self.assertIn("behavior_style:", workshop_source)
        self.assertIn("interaction_principles:", workshop_source)
        self.assertIn("function renderFirstUsePanel", workshop_source)
        self.assertIn("function selectWorkshopPack", workshop_source)
        self.assertIn("card.dataset.selectPack = pack.id", workshop_source)
        self.assertIn('card.setAttribute("aria-current", isEditing ? "true" : "false")', workshop_source)
        self.assertIn("function buildPackReadinessIssues", workshop_source)
        self.assertIn("function buildNoOutfitsState", workshop_source)
        self.assertIn("function buildNoEmotionsState", workshop_source)
        self.assertIn("function inferEmotionNameFromFileName", workshop_source)
        self.assertIn("async function uploadEmotionImages", workshop_source)
        self.assertIn("MAX_CHARACTER_PACK_ZIP_BYTES", workshop_source)
        self.assertIn("MAX_PORTRAIT_IMAGE_BYTES", workshop_source)
        self.assertIn("function yieldToUiForLargeFileRead", workshop_source)
        self.assertIn("fileName: file.name", workshop_source)
        self.assertIn("async function createOutfit", workshop_source)
        self.assertIn('invoke("create_portrait_outfit"', workshop_source)
        self.assertIn('invoke("read_portrait_image"', workshop_source)
        self.assertIn('invoke("set_default_portrait"', workshop_source)
        self.assertIn("function chooseLocalFiles", workshop_source)
        self.assertIn("document.body.appendChild(fileInput)", workshop_source)
        self.assertIn("fileInput.multiple = multiple", workshop_source)
        self.assertIn("inferEmotionNameFromFileName(file.name", workshop_source)
        self.assertIn("function buildImageLoadError", workshop_source)
        self.assertIn("function loadCalibrationOutfitPreview", workshop_source)
        self.assertIn("getPortraitImageUrl(pack.id, state.outfit, emotion)", workshop_source)
        self.assertIn("function bindCalibrationBubbleControls", workshop_source)
        self.assertIn("function setBubbleAnchorFromPointer", workshop_source)
        self.assertIn("style: getCalibrationBubbleStyle()", workshop_source)
        self.assertIn("readSliderUnit(els.calBubbleX", workshop_source)
        self.assertNotIn("convertFileSrc(", workshop_source)
        self.assertIn("先创建服装，再在服装卡片中导入图片", workshop_html)
        self.assertIn("设为默认立绘", workshop_source)
        self.assertNotIn('prompt("表情名称', workshop_source)
        self.assertNotIn('prompt("新服装 ID', workshop_source)
        self.assertIn("当前默认立绘无效：", workshop_source)
        self.assertNotIn("缺少必要表情：", workshop_source)
        self.assertNotIn("建议添加：", workshop_source)
        self.assertIn('flashElement(els.draftStatus, "save-flash")', workshop_source)
        self.assertIn("function pulsePackCard", workshop_source)
        self.assertIn("function showCreateError", workshop_source)
        self.assertIn("appWindow.onCloseRequested", workshop_source)
        self.assertIn("function buildWorkshopSnapshotSignature", workshop_source)
        self.assertIn("if (signature === lastWorkshopSnapshotSignature)", workshop_source)
        self.assertIn("core:window:allow-destroy", tauri_capabilities)
        self.assertIn(".first-use-panel", workshop_css)
        self.assertIn(".asset-empty-state", workshop_css)
        self.assertIn(".emotion-empty-state", workshop_css)
        self.assertIn('.workshop-body[data-tab-panel="portraits"]', workshop_css)
        self.assertIn(".portrait-import-actions", workshop_css)
        self.assertIn(".portrait-cutout-status", workshop_css)
        self.assertIn(".portrait-cutout-actions", workshop_css)
        self.assertIn('.portrait-cutout-status[data-state="configured"]', workshop_css)
        self.assertIn(".image-load-error", workshop_css)
        self.assertIn("@keyframes workshop-soft-pulse", workshop_css)
        self.assertIn(".bubble-style-options", workshop_css)
        self.assertIn('@import "./pet-surface.css"', workshop_css)
        self.assertIn(".form-input", workshop_css)
        self.assertIn("width: 100%", workshop_css)
        self.assertIn(".form-field:has(textarea)", workshop_css)
        self.assertIn("position: sticky", workshop_css)
        self.assertIn(".pack-card-identity", workshop_css)
        self.assertIn(".detail-panel-actions", workshop_css)
        self.assertIn('@media (prefers-reduced-motion: reduce)', workshop_css)
        self.assertIn('.workshop-body[data-tab-panel="list"]', workshop_css)

        self.assertIn('entry("persona_form".to_string())', tauri_source)
        self.assertIn("fn create_portrait_outfit", tauri_source)
        self.assertIn("fn read_portrait_image", tauri_source)
        self.assertIn("fn activate_character_pack", tauri_source)
        self.assertIn("struct CharacterPackActivationResult", tauri_source)
        self.assertIn("state.character_pack_id = pack_id.clone()", tauri_source)
        self.assertIn("CHARACTER_PACK_ACTIVATED_EVENT", workshop_source)
        self.assertIn("emit(CHARACTER_PACK_ACTIVATED_EVENT, { packId: activePackId })", workshop_source)
        self.assertNotIn("packId === view.activePackId) return", workshop_source)
        self.assertNotIn("applyBtn.disabled = isActive || Boolean(view.pendingApplyPackId)", workshop_source)
        self.assertIn("applyBtn.disabled = Boolean(view.pendingApplyPackId)", workshop_source)
        self.assertIn('"重新应用"', workshop_source)
        self.assertNotIn("main_window.reload()", tauri_source)
        self.assertIn("write_text_atomic(&path, &raw_state)", tauri_source)
        self.assertNotIn("app.emit_to(", tauri_source)
        self.assertIn("fn set_default_portrait", tauri_source)
        self.assertIn("tauri::ipc::Response::new(bytes)", tauri_source)
        self.assertNotIn("if emotions.is_empty() {\n            continue;", tauri_source)
        self.assertIn("fn pack_characters_dir", tauri_source)
        self.assertIn('safe_child_path(&asset_root_dir, "characters")', tauri_source)
        self.assertNotIn('pack_dir.join(&asset_root).join("characters")', tauri_source)
        self.assertNotIn('if clean.is_empty() { "default".to_string() }', tauri_source)
        self.assertIn('const DATA_ROOT_ENV: &str = "AKANE_DATA_ROOT";', tauri_source)
        self.assertIn('akane_data_root()?.join("characters")', tauri_source)
        self.assertIn("CHARACTER_PACK_TEMPLATE_JSON", tauri_source)
        self.assertIn("asset_protocol_scope()", tauri_source)
        self.assertNotIn('env!("CARGO_MANIFEST_DIR")', tauri_source)

    def test_next_character_runtime_state_is_pack_scoped(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")
        control_center_source = _read("desktop_pet_next/src/control-center-v2/bridge.js")
        data_sources = _read("desktop_pet_next/src/control-center/data-sources.js")
        tauri_source = _read("desktop_pet_next/src-tauri/src/main.rs")

        self.assertIn("characters: {}", main_source)
        self.assertIn("function getCharacterRuntimeKey", main_source)
        self.assertIn("function persistCurrentCharacterRuntimeState", main_source)
        self.assertIn("function applyCharacterRuntimeState", main_source)
        self.assertIn("persistCurrentCharacterRuntimeState(previousPackId)", main_source)
        self.assertIn("applyCharacterRuntimeState(pack.packId, pack.profile)", main_source)
        self.assertIn("resourceState.manifest = null", main_source)
        self.assertNotIn("seedFromCurrent: true", main_source)
        self.assertIn("listCharacterPacks().find((item) => item.id === requestedPackId)", main_source)
        self.assertIn("async function registerCharacterActivationBridge()", main_source)
        self.assertIn("async function applyPersistedCharacterActivation(packId)", main_source)
        self.assertIn("async function loadAndApplyPersistedCharacterState", main_source)
        self.assertIn("scheduleSnapshot: false", main_source)
        self.assertIn("void registerCharacterActivationBridge().catch", main_source)
        self.assertNotIn("await registerCharacterActivationBridge();", main_source)
        self.assertLess(
            main_source.index('let lastAppliedLayoutSignature = "";'),
            main_source.index("boot();"),
        )
        self.assertLess(
            main_source.index("let panelSyncTimer = null;"),
            main_source.index("boot();"),
        )
        self.assertIn("void registerSettingsBridge().catch", main_source)
        self.assertIn("setPetEmotion(state.currentEmotion, { persist: false, force: true });", main_source)
        self.assertIn("scheduleTauriRuntimeBridges();\n    await loadAndApplyPersistedCharacterState();", main_source)
        self.assertIn("window.setTimeout(startTauriRuntimeBridges, 0);", main_source)
        self.assertIn(
            "await reloadCharacterResources({ startup: true });\n    scheduleNativeWindowStateApply({ forceHitTest: true });",
            main_source,
        )
        self.assertNotIn("await syncNativeHitTest({ force: true });\n    await reloadCharacterResources", main_source)
        self.assertNotIn(
            'await invoke("apply_window_state", { state });\n    await applyCharacterLayoutResize();\n    scheduleNativeHitTestSync({ force: true });\n    await reloadCharacterResources',
            main_source,
        )
        self.assertIn("void Promise.allSettled([", main_source)
        self.assertIn("resolveAssetUrl(item.path || item.url || item.src", main_source)
        self.assertIn("function scheduleNativeWindowStateApply", main_source)
        self.assertIn("function canRenderCurrentLocalResources()", main_source)
        self.assertIn("function canUseBundledEmotionFallback()", main_source)
        self.assertIn("entry && !entry.url && canUseBundledEmotionFallback()", main_source)
        self.assertIn('packId === "akane_v1"', main_source)
        self.assertIn('emitTo("settings", SETTINGS_SNAPSHOT_EVENT, payload)', main_source)
        self.assertIn('emitTo("workshop", SETTINGS_SNAPSHOT_EVENT, payload)', main_source)
        self.assertIn('emitTo("workspace", SETTINGS_SNAPSHOT_EVENT, payload)', main_source)
        self.assertIn("settingsBridgeRegistered = true;\n  // Close the startup race", main_source)
        self.assertIn("await broadcastSettingsSnapshot();", main_source)
        self.assertIn("emit: emitMainEvent", control_center_source)
        self.assertIn('targetLabel: "main"', control_center_source)
        self.assertIn("createTargetedEventEmitter", control_center_source)
        self.assertEqual(
            control_center_source.count(
                'emitMainEvent(SETTINGS_COMMAND_EVENT, { command: "requestSnapshot" })'
            ),
            2,
        )
        self.assertNotIn('emitMainEvent({ command: "requestSnapshot" })', control_center_source)
        self.assertIn(
            "const [capabilitiesCatalog, voiceProfilesCatalog, approvalRequestsCatalog] = await Promise.all([",
            data_sources,
        )
        self.assertIn("const [next, modelRuntime, botCatalog] = await Promise.all([", control_center_source)
        self.assertIn("await refreshChatSession();", control_center_source)
        self.assertIn("loadOlderChatMessages", control_center_source)
        self.assertIn("mergeChatSessions", control_center_source)
        self.assertIn('buildBackendUrl(botBaseUrl, "/sessions/messages"', data_sources)
        self.assertIn('inferLatencyLabel(runtimeMetrics, ["tts", "asr"])', data_sources)
        self.assertIn('inferLatencyLabel(runtimeMetrics, ["capabilities.catalog"])', data_sources)
        self.assertNotIn('import * as mockData from "./mock-data.js";', data_sources)
        self.assertIn('const kind = options.kind || CONTROL_CENTER_SOURCE_KIND.backend;', data_sources)
        self.assertNotIn("if (kind === CONTROL_CENTER_SOURCE_KIND.mock)", data_sources)
        self.assertNotIn("...mockData", data_sources)
        self.assertNotIn('"预留"', data_sources)
        self.assertNotIn("buildPerceptionRuntimePatch", data_sources)
        self.assertNotIn("buildAdvancedAbilityOverview", data_sources)
        self.assertNotIn("buildAbilityWorkflows", data_sources)
        self.assertNotIn('"Live2D 预留状态"', data_sources)
        self.assertIn("withLiveRuntime", control_center_source)
        self.assertIn("buildCharacterRuntimePatchFromSettingsSnapshot", control_center_source)
        self.assertIn("buildMusicRuntimePatch", control_center_source)
        self.assertIn("characterRuntimeKey: getCharacterRuntimeKey(state.characterPackId)", main_source)
        self.assertIn("characters: buildCharacterRuntimeSnapshot()", main_source)
        self.assertIn("characters: HashMap<String, CharacterRuntimeState>", tauri_source)
        self.assertIn("for runtime in state.characters.values_mut()", tauri_source)

    def test_next_pet_state_carries_host_and_bound_bot_identity(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")
        rust_source = _read("desktop_pet_next/src-tauri/src/main.rs")

        self.assertIn("hostId: LOCAL_DEFAULT_INSTANCE_ID", main_source)
        self.assertIn("boundBotId: LOCAL_DEFAULT_INSTANCE_ID", main_source)
        self.assertIn("bindInstanceStorage(hostId)", main_source)
        self.assertIn("actualInstanceId !== state.hostId", main_source)
        self.assertIn("host_id: String", rust_source)
        self.assertIn("bound_bot_id: String", rust_source)
        self.assertIn('const BOUND_BOT_ID_ENV: &str = "AKANE_BOUND_BOT_ID"', rust_source)
        self.assertIn("normalize_pet_binding_ids(", rust_source)

    def test_control_center_selects_one_bound_bot_for_all_desktop_surfaces(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")
        panel_source = _read("desktop_pet_next/src/panel.js")
        workspace_source = _read("desktop_pet_next/src/workspace.js")
        control_center_source = _read("desktop_pet_next/src/control-center-v2/components/overview.js")
        control_center_bridge = _read("desktop_pet_next/src/control-center-v2/bridge.js")
        data_source = _read("desktop_pet_next/src/control-center/data-sources.js")
        action_router = _read("desktop_pet_next/src/control-center/action-router.js")
        bot_routing = _read("desktop_pet_next/src/bot-routing.js")

        self.assertIn('case "setBoundBot"', main_source)
        self.assertIn("await ensureBoundBotRegistered()", main_source)
        self.assertIn("scopeBackendEndpointToBoundBot", main_source)
        self.assertIn("botScopedPath(state.boundBotId", panel_source)
        self.assertIn("botScopedPath(state?.boundBotId", workspace_source)
        self.assertIn("data-bound-bot-select", control_center_source)
        self.assertIn('actionId === "settings.selectBot"', control_center_bridge)
        self.assertIn("createControlCenterDataSource(sourceOptions)", control_center_bridge)
        self.assertIn("readBotCatalog", data_source)
        self.assertIn('settingsSelectBot: "settings.selectBot"', action_router)
        self.assertIn('CONTROL_CENTER_ACTIONS.settingsSelectBot]: "setBoundBot"', data_source)
        self.assertIn("export function botScopedPath", bot_routing)
        self.assertIn('endpoint.startsWith("/api/qq/")', bot_routing)

    def test_next_care_runtime_uses_backend_authority_and_gates_shop_projection(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")
        panel_html = _read("desktop_pet_next/panel.html")
        panel_source = _read("desktop_pet_next/src/panel.js")
        shop_source = _read("desktop_pet_next/src/shop.js")
        feature_source = _read("desktop_pet_next/src/care-feature.js")

        self.assertIn("care: createUnresolvedCareFeature()", main_source)
        self.assertIn("applyCareFeatureStatus(resolveCareFeatureFromHealth(data))", main_source)
        self.assertIn("function stopCareRuntime()", main_source)
        self.assertIn("window.clearTimeout(carePassiveTimer)", main_source)
        self.assertIn("window.clearTimeout(careWorkTimer)", main_source)
        self.assertIn("if (!isCareRuntimeActive()) return false;", main_source)
        self.assertIn("attachDesktopCareContext({", main_source)
        self.assertIn("care: isCareRuntimeActive() ? normalizeCareState(state.care", main_source)
        self.assertIn('buildBackendEndpointUrl("care_snapshot", "/desktop-pet/care/snapshot"', main_source)
        self.assertIn('buildBackendEndpointUrl("care_action", "/desktop-pet/care/action"', main_source)
        self.assertIn("function applyAuthoritativeCareSnapshot", main_source)
        self.assertIn("legacy_state: isTauriRuntime ? legacyState : null", main_source)
        self.assertIn("careAuthorityImportedKeys", main_source)
        self.assertIn("care: null,", main_source)
        self.assertNotIn("function settleCarePassiveState", main_source)
        self.assertNotIn("function applyCareTurnCost", main_source)
        self.assertNotIn("function persistCareRuntimeChange", main_source)
        self.assertNotIn("function randomCareReward", main_source)
        self.assertIn("careFeature: { ...getCareFeatureStatus() }", main_source)
        self.assertIn(
            "shopAvailable: isCareRuntimeActive() && getProfileCareConfig().shopItems.length > 0", main_source
        )
        self.assertIn('id="btn-shop" type="button" hidden', panel_html)
        self.assertIn("function renderShopAvailability()", panel_source)
        self.assertIn("els.btnShop.hidden = !available;", panel_source)
        self.assertIn('if (typeof s.shopAvailable === "boolean") state.shopAvailable = s.shopAvailable;', panel_source)
        self.assertIn('await emitPanelAction({ action: "open-shop" });', panel_source)
        self.assertNotIn('openPanelOwnedWindow("open_shop_window", "open-shop")', panel_source)
        self.assertIn('els.summary.textContent = "养成模块未启用";', shop_source)
        self.assertIn('els.coins.textContent = "—";', shop_source)
        self.assertIn("delete result.desktop_care", feature_source)
        self.assertIn("resetCareEvaluationBaseline", feature_source)

    def test_next_pet_window_geometry_does_not_persist_stale_pixel_size(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")
        tauri_source = _read("desktop_pet_next/src-tauri/src/main.rs")

        self.assertIn("function applyWindowGeometryToState(geometry)", main_source)
        self.assertIn("state.width = null;", main_source)
        self.assertIn("state.height = null;", main_source)
        self.assertIn("width: null,\n    height: null,", main_source)
        self.assertIn("const activePackId = getCurrentCharacterPackId();", main_source)
        self.assertIn("buildCharacterPackOutfits(activePackId)", main_source)
        self.assertIn("fn saved_window_position_visible", tauri_source)
        self.assertIn("normalize_pet_state(&mut state)?;", tauri_source)
        self.assertIn("state.width = None;", tauri_source)
        self.assertIn("runtime.width = None;", tauri_source)

    def test_next_visual_renderer_has_static_portrait_adapter_boundary(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")
        renderer_source = _read("desktop_pet_next/src/visual-renderer.js")
        styles = _read("desktop_pet_next/src/styles.css")
        self.assertIn('@import "./pet-surface.css"', styles)
        styles += _read("desktop_pet_next/src/pet-surface.css")
        character_template = _read("desktop_pet_creator_kit/templates/character_pack/character.json")
        renderer_doc = _read("docs/desktop-pet-visual-renderer.md")

        self.assertIn('import { createVisualRenderer } from "./visual-renderer.js"', main_source)
        self.assertIn("const visualRenderer = createVisualRenderer", main_source)
        self.assertIn("visualRenderer.setCharacterLabel", main_source)
        self.assertIn("visualRenderer.setExpression", main_source)
        self.assertIn("visualRenderer.setMotion", main_source)
        self.assertIn("visual: visualRenderer.getStatus()", main_source)
        self.assertIn("STATIC_RENDERER_MODE", renderer_source)
        self.assertIn('"static_portrait"', renderer_source)
        self.assertIn("LIVE2D_PENDING_MODE", renderer_source)
        self.assertIn("live2dReady: false", renderer_source)
        self.assertIn("expressionImages: true", renderer_source)
        self.assertIn("cssMotion: true", renderer_source)
        self.assertIn("lipSync: false", renderer_source)
        self.assertIn("--bubble-anchor-x", renderer_source)
        self.assertIn("--bubble-anchor-y", renderer_source)
        self.assertIn("--bubble-max-width", renderer_source)
        self.assertIn("stage.dataset.bubbleStyle", renderer_source)
        self.assertIn("--bubble-anchor-x", styles)
        self.assertIn('.stage[data-bubble-style="paper"] .bubble', styles)
        self.assertIn('"style": "soft"', character_template)
        self.assertIn("let menuAnchor = null", main_source)
        self.assertIn("function repositionOpenMenu", main_source)
        self.assertIn('window.addEventListener("resize", () =>', main_source)
        self.assertIn("repositionOpenMenu();", main_source)
        self.assertIn("overscroll-behavior: contain", styles)
        self.assertIn(".quick-menu .menu-actions button:disabled", styles)
        self.assertIn("setExpression", renderer_doc)
        self.assertIn("Future Live2D Shape", renderer_doc)

    def test_next_system_media_awareness_is_read_only_activity_context(self) -> None:
        main_source = _read("desktop_pet_next/src/main.js")
        data_sources = _read("desktop_pet_next/src/control-center/data-sources.js")
        control_center_source = _read("desktop_pet_next/src/control-center-v2/components/overview.js")
        control_center_view_model = _read("desktop_pet_next/src/control-center-v2/view-model.js")
        tauri_source = _read("desktop_pet_next/src-tauri/src/main.rs")
        cargo_toml = _read("desktop_pet_next/src-tauri/Cargo.toml")

        self.assertIn("SYSTEM_MEDIA_POLL_MS", main_source)
        self.assertIn("SYSTEM_MEDIA_LYRICS_RETRY_MS", main_source)
        self.assertIn("SYSTEM_MEDIA_LYRICS_TURN_WAIT_FOCUSED_MS", main_source)
        self.assertIn("scheduleSystemMediaPoll({ immediate: true })", main_source)
        self.assertIn('tauriCall("get_current_system_media"', main_source)
        self.assertIn('buildBackendEndpointUrl("music_lyrics", "/capabilities/music/lyrics"', main_source)
        self.assertIn("function ensureSystemMediaLyrics", main_source)
        self.assertIn("const systemMediaLyricsRequests = new Map()", main_source)
        self.assertIn("function hydrateSystemMediaLyricsForTurn", main_source)
        self.assertIn("function shouldWaitForSystemMediaLyricsForTurn", main_source)
        self.assertIn("if (shouldWaitForSystemMediaLyricsForTurn(message, options))", main_source)
        self.assertIn('markTurnLatency("lyrics-hydration-background")', main_source)
        self.assertIn("const SYSTEM_MEDIA_LYRICS_TURN_WAIT_FOCUSED_MS = 2400", main_source)
        self.assertIn("lyrics_lookup_slow", main_source)
        self.assertIn("function buildSystemMediaLyricSnapshot", main_source)
        self.assertIn("function buildSystemMediaActivity", main_source)
        self.assertIn("function shouldUseSystemMediaActivity", main_source)
        self.assertIn("if (shouldUseSystemMediaActivity(systemActivity)) return excludePaused && systemActivity.status !== \"running\" ? null : systemActivity;", main_source)
        self.assertIn('source_kind: "system_media"', main_source)
        self.assertIn("system_media: true", main_source)
        self.assertIn("systemMedia: summarizeSystemMedia()", main_source)
        self.assertIn("systemLyrics: summarizeSystemMediaLyrics()", main_source)
        self.assertIn("lyric_status:", main_source)
        self.assertIn('controlTarget === "system"', data_sources)
        self.assertIn("legacySystemTrack", data_sources)
        self.assertIn("!Boolean(musicSnapshot.paused)", data_sources)
        self.assertIn("!Boolean(localDisplayName)", data_sources)
        self.assertIn("!Number(musicSnapshot.queueCount)", data_sources)
        self.assertIn("normalizeSystemMediaRuntime", data_sources)
        self.assertIn("lyricsReasonLabel", data_sources)
        self.assertIn("statusDetail", data_sources)
        self.assertIn("陪伴播放", control_center_source)
        self.assertIn("deriveMusic", control_center_view_model)
        self.assertIn("musicRuntime.bottomStatus", control_center_view_model)

        self.assertIn("struct SystemMediaSnapshot", tauri_source)
        self.assertIn("fn read_current_system_media_windows", tauri_source)
        self.assertIn("fn read_system_media_session", tauri_source)
        self.assertIn("manager.GetSessions()", tauri_source)
        self.assertIn('snapshot.playback_status == "playing"', tauri_source)
        self.assertIn("GlobalSystemMediaTransportControlsSessionManager::RequestAsync", tauri_source)
        self.assertIn("get_current_system_media", tauri_source)
        self.assertIn('"Media_Control"', cargo_toml)


class PetReachGestureT5ContractTests(unittest.TestCase):
    """T5: Verify "伸手" gesture wiring in main.js and styles.css."""

    @classmethod
    def setUpClass(cls) -> None:
        base = Path(__file__).parent.parent / "desktop_pet_next" / "src"
        cls.main_src = (base / "main.js").read_text(encoding="utf-8")
        cls.styles_src = (base / "portrait-motion.css").read_text(encoding="utf-8")
        assert '@import "./portrait-motion.css"' in (base / "styles.css").read_text(encoding="utf-8")

    def test_trigger_pet_reach_gesture_function_exists(self) -> None:
        self.assertIn("function triggerPetReachGesture()", self.main_src)

    def test_control_system_media_awaits_reach_gesture_before_tauri_call(self) -> None:
        self.assertIn("void triggerPetReachGesture()", self.main_src)
        reach_pos = self.main_src.index("void triggerPetReachGesture()")
        tauri_pos = self.main_src.index('tauriCall("control_system_media"', reach_pos)
        self.assertLess(reach_pos, tauri_pos)
        self.assertIn("controlSystemMediaPlayback(resolvedAction, { operationId })", self.main_src)

    def test_is_reaching_class_in_styles(self) -> None:
        self.assertIn("is-reaching", self.styles_src)

    def test_pet_reach_keyframe_in_styles(self) -> None:
        self.assertIn("pet-reach", self.styles_src)

    def test_smtc_action_case_in_handle_settings_command(self) -> None:
        self.assertIn('"smtcAction"', self.main_src)

    def test_final_activity_does_not_repeat_native_media_tool_execution(self) -> None:
        self.assertIn("function payloadHasSystemMediaExecution(payload)", self.main_src)
        self.assertIn('toolType === "system_media_control"', self.main_src)
        self.assertIn("if (payloadHasSystemMediaExecution(payload)) return;", self.main_src)

    def test_notifyMusicUnavailable_before_reach_gesture(self) -> None:
        unavailable_pos = self.main_src.index("notifyMusicActivityUnavailable")
        reach_pos = self.main_src.index("void triggerPetReachGesture()")
        self.assertLess(unavailable_pos, reach_pos)


class ProjectWorkspacePickerContractTests(unittest.TestCase):
    def test_host_path_stays_inside_tauri_and_public_ui_uses_project_ids(self) -> None:
        root = Path(__file__).parent.parent
        workspace_html = (root / "desktop_pet_next" / "workspace.html").read_text(encoding="utf-8")
        workspace_js = (root / "desktop_pet_next" / "src" / "workspace.js").read_text(encoding="utf-8")
        tauri_source = (root / "desktop_pet_next" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")

        self.assertIn('id="bind-project-directory"', workspace_html)
        self.assertIn('invoke("bind_project_directory")', workspace_js)
        self.assertIn('invoke("manage_project_workspaces"', workspace_js)
        self.assertNotIn('"host_directory":', workspace_js)
        self.assertNotIn("hostDirectory", workspace_js)
        self.assertIn("blocking_pick_folder", tauri_source)
        self.assertIn('"host_directory": directory.to_string_lossy()', tauri_source)
        self.assertIn("project_binding_requires_local_backend", tauri_source)


class ListeningTogetherT6FrontendContractTests(unittest.TestCase):
    """T6A: Verify mood phrase display wiring in the canonical V2 overview."""

    @classmethod
    def setUpClass(cls) -> None:
        base = Path(__file__).parent.parent / "desktop_pet_next" / "src"
        cls.cc_src = (base / "control-center-v2" / "components" / "overview.js").read_text(encoding="utf-8")

    def test_mood_phrase_from_emotion_function_exists(self) -> None:
        self.assertIn("function moodPhraseFromEmotion(", self.cc_src)

    def test_mood_line_class_in_render_template(self) -> None:
        self.assertIn('class="mood-line"', self.cc_src)

    def test_current_expression_referenced_in_render(self) -> None:
        view_model = _read("desktop_pet_next/src/control-center-v2/view-model.js")
        self.assertIn("currentExpression", view_model)
        self.assertIn("vm.character.emotion", self.cc_src)


class FloatingPanelHandoffContractTests(unittest.TestCase):
    """Verify UI handoff v2 panel tasks stay wired through the main window."""

    @classmethod
    def setUpClass(cls) -> None:
        root = Path(__file__).parent.parent
        cls.panel_html = (root / "desktop_pet_next" / "panel.html").read_text(encoding="utf-8")
        cls.panel_js = (root / "desktop_pet_next" / "src" / "panel.js").read_text(encoding="utf-8")
        cls.panel_css = (root / "desktop_pet_next" / "src" / "panel.css").read_text(encoding="utf-8")
        cls.main_js = (root / "desktop_pet_next" / "src" / "main.js").read_text(encoding="utf-8")
        cls.workspace_js = (root / "desktop_pet_next" / "src" / "workspace.js").read_text(encoding="utf-8")
        cls.tauri_rs = (root / "desktop_pet_next" / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")

    def test_panel_theme_toggle_persists_locally(self) -> None:
        self.assertIn('id="theme-toggle-btn"', self.panel_html)
        self.assertIn('[data-theme="dark"]', self.panel_css)
        self.assertIn("function applyTheme(theme)", self.panel_js)
        self.assertIn('localStorage.setItem("panel-theme"', self.panel_js)
        self.assertIn('localStorage.getItem("panel-theme")', self.panel_js)

    def test_panel_music_state_uses_event_bridge_not_direct_backend(self) -> None:
        self.assertIn('id="music-controller-badge"', self.panel_html)
        self.assertIn('"refresh-co-listen"', self.panel_js)
        self.assertIn('"refresh-music-controller"', self.panel_js)
        self.assertIn('"set-music-controller"', self.panel_js)
        self.assertIn("function refreshPanelCoListenSummary()", self.main_js)
        self.assertIn("function refreshPanelMusicController()", self.main_js)
        self.assertIn("function setPanelMusicController(controller)", self.main_js)
        self.assertIn('emitTo("panel", eventName, payload)', self.main_js)
        self.assertIn('emitTo("main", "panel:action", payload)', self.panel_js)
        self.assertIn('emitTo("main", SETTINGS_COMMAND_EVENT, payload)', self.workspace_js)
        self.assertIn("musicController: panelMusicController", self.main_js)
        self.assertNotIn('/capabilities/music/co_listen_summary"', self.panel_js)
        self.assertNotIn('/capabilities/music/control_permissions"', self.panel_js)

    def test_panel_workspace_and_workshop_buttons_can_open_without_main_event_bridge(self) -> None:
        self.assertIn('id="btn-workspace"', self.panel_html)
        self.assertIn('id="btn-workshop"', self.panel_html)
        self.assertIn("function openPanelOwnedWindow(command, action)", self.panel_js)
        self.assertIn('openPanelOwnedWindow("open_workspace_window", "open-workspace")', self.panel_js)
        self.assertIn('openPanelOwnedWindow("open_workshop_window", "open-workshop")', self.panel_js)
        self.assertIn("async fn open_workspace_window", self.tauri_rs)
        self.assertIn("async fn open_workshop_window", self.tauri_rs)

    def test_macos_music_control_uses_applescript_and_linux_stays_structured(self) -> None:
        self.assertIn('cfg(target_os = "macos")', self.tauri_rs)
        self.assertIn("fn control_system_media_macos", self.tauri_rs)
        self.assertIn('Command::new("osascript")', self.tauri_rs)
        self.assertIn('tell application "Music" to play', self.tauri_rs)
        self.assertIn("TryPlayAsync", self.tauri_rs)
        self.assertIn("TryPauseAsync", self.tauri_rs)
        self.assertIn("TrySkipNextAsync", self.tauri_rs)
        self.assertIn("TrySkipPreviousAsync", self.tauri_rs)
        self.assertIn("TryStopAsync", self.tauri_rs)
        self.assertNotIn("SendInput", self.tauri_rs)
        self.assertIn("TODO: Linux MPRIS", self.tauri_rs)
        self.assertIn('system_media_control_unavailable(action, "unsupported_platform"', self.tauri_rs)


if __name__ == "__main__":
    unittest.main()
